version: '3.9'
services:

  rinha-micronaut-1:
    image: openjdk:17-ea-5-jdk-alpine
    container_name: rinha-micronaut-1
    hostname: rinha-micronaut-1
    volumes:
      - ./target/rinhav4-0.1.jar:/rinhav4-0.1.jar
    ports:
      - '9991:9991'
    expose:
      - 9991
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - POSTGRES_DB_NAME=rinha
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgresql
      - SERVER_PORT=9991
      - OTHER_API_URL=http://rinha-micronaut-2:9992
      - REDIS_HOST=rinha-redis:6379
    networks:
      - rinhav4-network
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: '512MB'
    command: java -jar rinhav4-0.1.jar

  rinha-micronaut-2:
    image: openjdk:17-ea-5-jdk-alpine
    container_name: rinha-micronaut-2
    hostname: rinha-micronaut-2
    volumes:
      - ./target/rinhav4-0.1.jar:/rinhav4-0.1.jar
    ports:
      - '9992:9992'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - POSTGRES_DB_NAME=rinha
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgresql
      - SERVER_PORT=9992
      - OTHER_API_URL=http://rinha-micronaut-1:9991
      - REDIS_HOST=rinha-redis:6379
    networks:
      - rinhav4-network
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: '512MB'
    command: java -jar rinhav4-0.1.jar

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    hostname: rinha-redis
    ports:
      - "6379:6379"
    networks:
      - rinhav4-network

  nginx:
    image: nginx:1.24-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-micronaut-1
      - rinha-micronaut-2
    ports:
      - "9999:9999"
#    network_mode: host
    expose:
      - 9999
#    deploy:
#      resources:
#        limits:
#          cpus: '0.15'
#          memory: '512MB'
    networks:
      - rinhav4-network

  postgresql:
    container_name: rinha-database-micro
    image: postgres:14.10
    hostname: postgresql
    command: 'postgres -c max_connections=210 -c shared_buffers=512MB -c wal_buffers=64MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    deploy:
#      resources:
#        limits:
#          cpus: '0.35'
#          memory: '1024MB'
    networks:
      - rinhav4-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  rinhav4-network: